// The surface ownership map: same data as the shared Google Sheet
// (`26_0910 Audit/delivery/surface-ownership-map.csv`), plus a one-line
// finding per surface (the xlsx's "Issue (1 line)" column, F-number
// citations stripped). No scores, no F-numbers, no other evidence.
// Names shortened from the source sheet per Jon's edits (Sep 2026); "Paid
// ads (current)" and "Paid ads (historical explorations)" were merged into
// one "Paid ads" row, and "Reel" is a new addition, not from the xlsx.
// The Events sub-group (Sep 22) replaced the single "In-person events" row.
//
// `photos` lists image keys, resolved against data.json's images (the audit
// export) plus PHOTOS below for anything added by hand. Files live in
// public/aleph/audit/img as <key>.webp (thumb) and <key>-lg.webp (full).
export const SURFACES = [
  { group: 'Communication', sub: 'Visual', surface: 'Mark', owner: 'Red Antler', what: "The triquetra mark and how it's used: color, size, placement.", finding: 'The triquetra carries the Borges story, which takes a paragraph to explain and says nothing about finance or trust. It also ships in an unofficial blue on Microsoft Marketplace.' },
  { group: 'Communication', sub: 'Visual', surface: 'Wordmark', owner: 'Red Antler', what: 'The "aleph" logotype that sits next to the symbol.', finding: 'Letterforms have little character, and the counter of the "p" looks off center.' },
  { group: 'Communication', sub: 'Visual', surface: 'Typography', owner: 'Red Antler', what: 'Söhne and IBM Plex Mono in marketing, Inter in the product.', finding: 'Söhne reads professional and simple with the barest character; a lot of small type (see the quotes). The product runs on Inter only.' },
  { group: 'Communication', sub: 'Visual', surface: 'Color', owner: 'Red Antler', what: 'The black-and-white palette plus the accent Red Antler picks.', finding: 'Black and white reads corporate, and purple marks AI features, which makes AI look like an add-on. The symbol turns blue on Microsoft Marketplace.' },
  { group: 'Communication', sub: 'Visual', surface: 'Icons', owner: 'Shared', what: 'UI and marketing icons.', finding: "Fine but generic, and not doing much to explain things. The product runs on FontAwesome today, a hodgepodge of sets in practice{{Daniel, Sep 17: custom product icons aren't strategic. The investment belongs in higher-fidelity drawings, diagrams and animation.}}." },
  { group: 'Communication', sub: 'Visual', surface: 'Motion', owner: 'Red Antler', what: 'How things move: the logo animation, ad and video motion, lower thirds.', finding: 'Not much motion today: the spinning mark on product load, a simple wordmark animation in videos, the new launch logo animation, and light motion on the launch page (likely motion.dev). Lower thirds need some zhuzh.' },
  { group: 'Communication', sub: 'Visual', surface: 'Photography', owner: 'Aleph', what: 'Headshots and team photos on the site.', finding: 'Headshots and team photos. Nothing wrong with either, but not unique.' },
  { group: 'Communication', sub: 'Visual', surface: 'Merch', owner: 'Red Antler', what: 'Apparel and swag.', finding: "One piece works: the Aleph baby onesie sent to customers and prospects having a baby{{Daniel, Sep 17. Merch is a deliverable in the Red Antler work.}}." },
  { group: 'Communication', sub: 'Visual', surface: 'Data viz', owner: 'Red Antler', what: 'A drawing style for explaining how Aleph works and for charts in marketing.', finding: 'Badly needs help: confusing and hard to parse, in webinar decks and across the site{{Daniel holds up Sapien, an adjacent competitor, for polish and diagrams in ads (granola, Jul 30).}}. The team knows it.' },
  { group: 'Communication', sub: 'Visual', surface: 'DAM', owner: 'Aleph', assigned: 'Jon', what: 'One place to grab approved logos, images and videos. Air today.', finding: "Air works fine, but it's underused." },
  { group: 'Communication', sub: 'Visual', surface: 'design.md', owner: 'Shared', assigned: 'Jon', what: 'A text file of brand rules that AI tools read to make on-brand work.', finding: 'Doesn\'t exist yet{{Vercel is one of the brand references leadership likes (brand-revamp), which is where the "Vercel-style" naming for this surface comes from.}}.' },
  { group: 'Communication', sub: 'Verbal', surface: 'Positioning line', owner: 'Red Antler', what: 'The one sentence for what Aleph is and why it wins.', finding: 'Our homepage headline is nearly Drivetrain\'s{{Aleph: "AI-native FP&A that connects your data, strategy, and spreadsheets." Drivetrain: "The AI-native FP&A platform that does the work."}}, and "AI-native" appears on no other page.' },
  { group: 'Communication', sub: 'Verbal', surface: 'Messaging hierarchy', owner: 'Red Antler', what: 'The ranked messages under the positioning line: pillars, proof points, versions per audience.', finding: 'There isn\'t one. The site leads with FP&A on 16 pages and trust on two{{The Agent page and the AI overview page, the only 2 of 37 pages crawled that use the word "trust."}}, and the copy was pieced together over many rounds.' },
  { group: 'Communication', sub: 'Verbal', surface: 'Voice & tone guide', owner: 'Red Antler', what: 'How Aleph sounds, with examples, for people and for AI tools.', finding: 'There isn\'t one. The site swings between technical manual, hype{{"Mission control for your mission-critical metrics" (Dashboards). "...the flexibility of spreadsheets, and the magic of AI" (Homepage subhead). "Give your portcos and portfolio superpowers" (PE-backed).}} and sales push. Charlie\'s voice and tone survey exists as input, and Daniel is spending a half day with him in Boulder the week of Sep 21 to force a v1 before creative exploration starts in October{{Daniel, Sep 17. Red Antler\'s version leans toward headlines, messaging hierarchy and positioning, so the written voice guide is ours to land first.}}.' },
  { group: 'Communication', sub: 'Verbal', surface: 'Headlines', owner: 'Red Antler', what: 'Page, ad and email headlines, plus CTA labels like "Book a demo."', finding: 'The demo goes by six names{{"Book a demo" (109 uses), "Get a Demo" (85), "Get a demo" (13), "Schedule a personalized demo" (4), "Talk to an expert" (2), and the exit modal\'s "Talk to our experts." Counted across 36 pages.}}, "Discover Aleph today" closes 11 pages{{The phrase repeats as a closing line on 11 of the 37 pages crawled (messaging-and-voice.md, Sep 13).}}, and two pages have no headline{{The PE-backed page and the AI spend calculator.}}.' },
  { group: 'Communication', sub: 'Verbal', surface: 'Value props', owner: 'Red Antler', what: 'How features are named and described.', finding: 'One agent has three names{{Aleph Agent, Aleph MCP and "Aleph Agent MCP" are one agent reached through different doors. The agent does the work, Slack and the web app are its home, and the MCP is the plug that lets Claude or ChatGPT use it. The site uses both "Aleph MCP" and "Aleph Agent MCP," and the launch copy says "Aleph Agent… all powered by the Aleph MCP."}}, and feature copy reads like a technical manual.' },
  { group: 'Communication', sub: 'Verbal', surface: 'Marketplace listing', owner: 'Aleph', priority: 'urgent', photos: ['icon-excel', 'icon-google'], what: 'Name, description and screenshots in app stores: Microsoft AppSource, Google Workspace, Slack, ChatGPT and Claude.', finding: 'Boilerplate, and it disagrees with the site: 150+ vs 200+ integrations, setup in minutes vs days{{Site: "150+ integrations," trial promises "minutes, not months." Sage Intacct listing: "200+ integrations," "days, not weeks or months."}}. The add-in and extension logos (Excel, PowerPoint, ChatGPT, Claude, Cursor, Slack) are in the Red Antler brief{{Daniel, Sep 17.}}.' },

  { group: 'Marketing', sub: 'Growth', surface: 'Paid ads', owner: 'Red Antler', assigned: 'Miles', priority: 'urgent', what: 'LinkedIn and Meta ads running now, and past ad concepts in Figma.', finding: 'Creative reads junior{{Tsering, Red Antler kickoff notes, Aug 26: "Creative is junior and unintentional; messaging is too granular and feature-heavy."}} and feature-heavy, and competitors outspend us roughly 50x{{Reid flagged Q2 inbound at 91% of target before OK\'ing the Red Antler spend (brand-revamp, Jul 17 and Aug 26).}}. The plainest comp wins on resonance{{Daniel, gdm-aleph-team, Sep 3: what works for ads and messaging isn\'t intuitive.}}.' },
  { group: 'Marketing', sub: 'Growth', surface: 'Organic social', owner: 'Red Antler', priority: 'hold', photos: ['linkedin'], what: "Aleph's LinkedIn, X, Instagram and YouTube profiles and posts.", finding: 'The channels post, and nothing ties the posts together. Almost all talk about us comes from us{{LinkedIn/X search, Sep 11: recent posts are new-hire welcomes, Albert\'s Agentic Budgeting launch post and employee reshares. No unprompted customer posts found on either platform.}}.' },
  { group: 'Marketing', sub: 'Growth', surface: 'Ebooks', owner: 'Red Antler', assigned: 'Theresa (covers)', priority: 'invest', what: 'Ebooks and guides, gated behind an email form.', finding: 'Deep topics resonate{{Red Antler kickoff notes, Aug 26: "deep, technical topics resonate" (example: "AI skills for finance"), but "nothing passes the scroll-stop test." Idea floated: treat each cover like a magazine, fresh but with through-lines.}}, and every cover looks like the same template. Daniel wants the magazine-cover approach to go further: same template, fresh cover art and spot illustrations, at roughly 40 hours over two weeks instead of 20{{Daniel, Sep 17, on Theresa\'s last three covers.}}.' },
  { group: 'Marketing', sub: 'Growth', surface: 'Webinars', owner: 'Aleph', priority: 'invest', what: 'Live and recorded sessions, often with a partner.', finding: 'Works with the right partner{{Rillet webinar, ~800 signups. Rillet is also an integration and, per Adam, a Red Antler client (brand-revamp, Aug 26 and Jun 26).}}, quarterly today with a monthly goal, and takes 3 hours of manual promo each. Not every partner says yes{{Numeric declined a joint webinar because the products are now too competitive (brand-revamp, Jul 30).}}. Recordings are scattered, and the site has no webinars page.' },
  { group: 'Marketing', sub: 'Growth', surface: 'Email', owner: 'Aleph', assigned: 'Jack (HubSpot)', priority: 'discuss', what: 'Marketing email in HubSpot: newsletters and launch emails.', finding: 'No email templates or design system in HubSpot{{gdm-aleph-team, Sep 1.}}, and HubSpot sends nothing after a demo or trial request{{HubSpot, Sep 18: no confirmation, nurture, trial or welcome email among 198 marketing emails, and no onboarding or nurture workflow among 378.}}.' },
  { group: 'Marketing', sub: 'Growth', surface: 'Zoom waiting-room loop', owner: 'Red Antler', what: 'The animation prospects see while waiting for a sales call.', finding: "Doesn't exist yet." },
  { group: 'Marketing', sub: 'Growth', surface: 'Launch template', owner: 'Aleph', what: 'Posts, videos and GIFs for each launch.', finding: 'Good moments, like the Series B and Agentic Budgeting, with no throughline between them{{The launch had separate directions for video, page, ebook and email, and there\'s no single campaign system yet (agentic-budgeting, Aug 31).}}.' },
  { group: 'Marketing', sub: 'Growth', surface: 'Podcast (10X Finance)', owner: 'Aleph', what: 'The 10X Finance podcast.', finding: 'Hard to find on the site.' },
  { group: 'Marketing', sub: 'Growth', surface: 'Youtube profile', owner: 'Aleph', priority: 'invest', what: 'The YouTube channel, and launch and demo videos.', finding: 'Voiceovers are hard to follow, and lower thirds and thumbnails need work. A net-new tutorial library is the plan for relaunching the channel{{Daniel, Sep 17.}}.' },
  { group: 'Marketing', sub: 'Growth', surface: 'Video tutorials', owner: 'Aleph', priority: 'invest', what: 'A net-new library of short product tutorials.', finding: "Doesn't exist yet. Daniel wants it built and used to relaunch the YouTube channel{{Daniel, Sep 17.}}." },
  { group: 'Marketing', sub: 'Growth', surface: 'Reel', owner: 'Aleph', priority: 'hold', what: 'A highlight reel cutting together product, culture and customer moments.', finding: '' },
  { group: 'Marketing', sub: 'Growth', surface: 'Youtube thumbs', owner: 'Aleph', priority: 'invest', what: 'Thumbnails for the @get-aleph channel.', finding: 'No thumbnail system today.' },
  { group: 'Marketing', sub: 'Events', surface: 'Event format', owner: 'Aleph', priority: 'discuss', photos: ['event-room', 'event-food', 'event-entry'], what: 'In-person sessions like agentic budgeting: the room, the food, the run of show.', finding: 'Running now, at Mindspace. A room of finance leaders is the customer voice the rest of the brand is missing, so it\'s worth planning what we capture each time: quotes, photos, the share-outs.' },
  { group: 'Marketing', sub: 'Events', surface: 'Standing banner', owner: 'Aleph', photos: ['event-banner', 'event-entry'], what: 'The pull-up banner at the door.', finding: 'Customer logos up front is the right call. The line leads with "AI-native FP&A," the same phrase as the homepage and Drivetrain.' },
  { group: 'Marketing', sub: 'Events', surface: 'Badges and lanyards', owner: 'Aleph', photos: ['event-badges'], what: 'Name badges, holders and lanyards at check-in.', finding: 'Clean and legible, with name, title and company. No Aleph mark on them that I can see.' },
  { group: 'Marketing', sub: 'Events', surface: 'Table tents', owner: 'Aleph', what: 'Signs on the tables: agenda, Wi-Fi, prompts.', finding: '' },
  { group: 'Marketing', sub: 'Events', surface: 'Swag (water bottle, fidget cube)', owner: 'Shared', photos: ['event-bottle', 'event-fidget'], what: 'Giveaways on the tables and at the door.', finding: 'Good objects, black with a laser-etched mark. The cube adds "Stress-free FP&A," a third tagline next to the banner\'s and the homepage\'s.' },
  { group: 'Marketing', sub: 'Events', surface: 'Presentation and activities', owner: 'Aleph', what: 'The slide deck, plus activities inside it: one word for budgeting, name, company and role.', finding: 'The one-word share-out is free customer language. Worth writing down every time.' },
  { group: 'Marketing', sub: 'Sales', surface: 'Sales deck', owner: 'Red Antler', assigned: 'WildFruit', what: 'The 12-slide deck sales uses in demos.', finding: "I don't have access yet." },
  { group: 'Marketing', sub: 'Sales', surface: 'Investor deck', owner: 'Aleph', what: 'The fundraising and board deck.', finding: "I don't have access yet." },
  { group: 'Marketing', sub: 'Sales', surface: 'One pagers', owner: 'Aleph', priority: 'discuss', what: 'Leave-behinds and customer stories for sales.', finding: "Four case study pages on the site. I haven't reviewed them in depth yet." },
  { group: 'Marketing', sub: 'Sales', surface: 'Knowledge base', owner: 'Aleph', what: 'Where customers learn and get help: docs, how-tos and videos.', finding: 'Docs, how-tos and videos are scattered{{Daniel, Sep 11: videos, webinars and trainings are scattered across the knowledge base.}}, and the videos are hard to follow.' },
  { group: 'Marketing', sub: 'Sales', surface: 'Onboarding drip campaign', owner: 'Aleph', priority: 'discuss', what: 'Automated emails that teach new users after they sign.', finding: 'Doesn\'t exist, and there\'s interest in one. Onboarding is all CSM, so a new customer\'s first guided experience is a person{{Daniel, Slack: "\'AI for finance\' in part means \'you don\'t need to use or learn the web app,\' which sort of changes what we should do with the drip campaign for onboarding."}}. Nobody has built it, so the rebrand can design it from scratch. Whether it\'s brand\'s job or CX\'s is still open.' },
  { group: 'Marketing', sub: 'Sales', surface: 'Forms (demo, trial, contact)', owner: 'Aleph', assigned: 'Jack (HubSpot, Default)', photos: ['flow-03', 'trial', 'contact', 'flow-04'], what: 'The HubSpot forms behind every CTA.', finding: 'HubSpot styling, a contact form that asks the most, and a trial that HubSpot logs as a demo request{{HubSpot, Sep 18: a trial submission sets the "Demo Request Submission Date," runs the same workflows as a demo, and a booked meeting creates a sales deal. Nothing creates an account.}}. The demo form converts 15.5% of the people who see it, and 79% of them never start it{{HubSpot form analytics, Aug 20 to Sep 18: 723 views, 112 submissions. Trial 16.9%, contact 15.2%.}}, so the drop happens on the page before anyone types. Cheap to change, outside Red Antler\'s scope, and measurable against that baseline.' },
  { group: 'Marketing', sub: 'Sales', surface: 'Scheduler and routing (Default)', owner: 'Aleph', assigned: 'Jack', what: 'Default.com, the step after the demo form: it qualifies the lead, shows a calendar and assigns a salesperson.', finding: 'Default qualifies the lead and shows qualified buyers a calendar{{Jack\'s Sep 8 tests on the Agentic Budgeting form: qualified submits booked, some went through without a booking, and one with no company data was sent to an extra form.}}. Before it, one line of HubSpot text ("someone will be in touch shortly"). After it, a calendar invite and the rep.' },
  { group: 'Marketing', sub: 'Sales', surface: 'Reviews and badges (G2)', owner: 'Aleph', what: 'G2 reviews and badges, and how we show them on the site and in ads.', finding: 'We lean hard on G2 badges{{G2: 4.9 out of 5 from 108 reviews.}}, and I don\'t know yet whether buyers give them weight.' },
  { group: 'Marketing', sub: 'Sales', surface: 'Deck system (webinars, walkthroughs, internal)', owner: 'Shared', assigned: 'WildFruit (sales deck only)', what: 'Every other deck we present: webinars, walkthroughs, internal meetings, CSM calls.', finding: 'Plain and static, and it shows up everywhere: video walkthroughs, webinars, the sales and investor decks, internal meetings and likely CSM calls.' },

  { group: 'Product', sub: 'App', surface: 'Sign-in (Auth0)', owner: 'Aleph', priority: 'invest', photos: ['flow-07'], what: 'The login page at app.getaleph.com.', finding: "A stock Auth0 page with a blue button the site doesn't use and no sign-up link." },
  { group: 'Product', sub: 'App', surface: 'Product onboarding', owner: 'Aleph', assigned: 'CX (CSM-led today)', what: 'What a new user sees their first time in the app.', finding: 'No first-run. You land in the app and a CSM does the teaching{{Daniel, Sep 11: "We still need to educate users and guide them. That\'s non-negotiable."}}.' },
  { group: 'Product', sub: 'App', surface: 'MCP (incl. preview screenshots)', owner: 'Aleph', priority: 'urgent', what: 'How Aleph looks inside Claude, ChatGPT and Cursor, and the screenshots that show it on the site, in directories and in ads.', finding: 'The preview screenshots are the first thing a Claude or ChatGPT user sees of us, and they\'re generic and low-res. The MCP itself looks different in Claude, ChatGPT, Cursor and the app{{Daniel, Sep 11: product marketing needs a platform-agnostic treatment.}}.' },
  { group: 'Product', sub: 'App', surface: 'The Agent', owner: 'Aleph', what: 'The agent inside the web app: name, icon, color, working states and how it writes.', finding: 'Chat sits low on the page and is easy to miss, and purple marks what the agent does.' },
  { group: 'Product', sub: 'App', surface: 'Slack agent', owner: 'Aleph', what: 'The Aleph app in Slack: icon, name, bot avatar, and how answers and alerts look.', finding: "I haven't reviewed it in depth yet." },
  { group: 'Product', sub: 'App', surface: 'Excel add-in', owner: 'Aleph', what: 'The Aleph sidebar and ribbon inside Excel, plus its AppSource listing.', finding: 'The icon ships in an unofficial blue on Microsoft Marketplace.' },
  { group: 'Product', sub: 'App', surface: 'ChatGPT / Claude / Cursor extensions', owner: 'Shared', what: "Aleph's entry in each AI tool's app directory: icon, name, description, gallery.", finding: "Our directory entries are text only. Hex's show the product." },
  { group: 'Product', sub: 'App', surface: 'In-product data viz', owner: 'Shared', priority: 'discuss', what: 'Charts, tables and KPI cards in the app and dashboards.', finding: 'Inter and a SaaS-kit feel. Past the logo, very little says Aleph (v2 is coming, so I hold this lightly). Red Antler sets the data-viz style; how much of it reaches the product is a discussion with Sam Crank, who leads front-end{{Daniel, Sep 17: more about what\'s intuitive for finance customers than a brand exercise.}}.' },
  { group: 'Product', sub: 'App', surface: 'PowerPoint add-in', owner: 'Aleph', what: '"Aleph for PowerPoint," which syncs live charts into slides.', finding: "Blue icon on Microsoft Marketplace, and it's missing from Red Antler's app icon list." },
  { group: 'Product', sub: 'App', surface: 'Empty and loading states', owner: 'Aleph', priority: 'oob', what: "What the app shows before there's data, or while the agent works.", finding: 'A logo spinner on load, and little else. Loading stays a simple rendition of the logo. Empty states are where brand can go, with richer per-view illustration{{Daniel, Sep 17, holding up Linear\'s engineering-drawing empty states.}}.' },
  { group: 'Product', sub: 'Web', surface: 'Homepage', owner: 'Shared', priority: 'invest', photos: ['home-aleph', 'home-drivetrain'], what: 'The front door at getaleph.com.', finding: 'The headline is close to Drivetrain\'s{{Aleph: "AI-native FP&A that connects your data, strategy, and spreadsheets." Drivetrain: "The AI-native FP&A platform that does the work."}}, and on a phone the page takes about 32 seconds to show content. Albert has let the site sit at "average at best" for years{{Albert "hates bad design" but has let the site and decks sit at "average at best" for years. Reid: brand won\'t hit many barriers here (granola, Sep 1).}}. A website refresh is funded at $200k with MetaLab as the creative and engineering accelerator, kicking off as the Red Antler work wraps{{Daniel, Sep 17.}}.' },
  { group: 'Product', sub: 'Web', surface: 'Product pages', owner: 'Aleph', priority: 'invest', what: 'The Platform pages: add-ins, dashboards, security and the AI pages.', finding: 'AI still gets its own menu column, though no longer its own purple{{Platform menu, Sep 18: "Core platform" and "AI capabilities" columns, both in the same neutral styling.}}, and seven AI pages describe one agent.' },
  { group: 'Product', sub: 'Web', surface: 'Solutions pages', owner: 'Aleph', what: 'The job and buyer pages: budgeting, PE, VC, fractional CFOs and the rest.', finding: 'Nearly the same template with the headline swapped. One respondent said the PE page could be a different company from the Agent page{{Internal brand survey, Jul 2026: "Various pages across the website feel entirely disconnected from one another," and the PE page "could be for an entirely different company" than the Agent page.}}.' },
  { group: 'Product', sub: 'Web', surface: 'Pricing', owner: 'Aleph', what: 'A pricing page on the site.', finding: 'No page. /pricing returns a 404.' },
  { group: 'Product', sub: 'Web', surface: 'Docs', owner: 'Aleph', what: 'Help docs at docs.getaleph.com.', finding: 'Behind the product login, though that\'s loosening{{Daniel, Sep 11: changelog and docs access is opening up.}}, with recorded walkthroughs that are hard to follow.' },
  { group: 'Product', sub: 'Web', surface: 'Blog', owner: 'Shared', what: 'Posts and their hero images.', finding: 'Deep technical topics perform, and every post uses the same template.' },
  { group: 'Product', sub: 'Web', surface: 'Changelog', owner: 'Aleph', assigned: 'Adam', what: 'The running list of product updates.', finding: 'Behind login today, though that\'s loosening{{Daniel, Sep 11: changelog and docs access is opening up.}}.' },
  { group: 'Product', sub: 'Web', surface: 'Careers', owner: 'Aleph', what: 'The careers page and job posts.', finding: "I haven't reviewed it in depth yet." },
  { group: 'Product', sub: 'Web', surface: 'Footer / IA', owner: 'Aleph', what: "The site's nav, footer and page structure.", finding: '37 pages in seven groups{{Core platform (4), AI (7), solutions by job (4), solutions by buyer (4), proof and service (2), lead gen (7), company and conversion (5).}}, with AI split out from the core platform.' },
  { group: 'Product', sub: 'Web', surface: 'SEO', owner: 'Aleph', what: 'Moving the site from getaleph.com to aleph.ai, which Aleph already owns.', finding: '"Aleph" is hard to own. We rank third for our own name{{Plain "aleph" search: 1st Google\'s AI answer, 2nd Wikipedia\'s entry on the Hebrew letter, 3rd getaleph.com.}}.' },
  { group: 'Product', sub: 'Web', surface: 'Search presence (branded, organic, paid, AI answers)', owner: 'Aleph', photos: ['serp-brand', 'serp-ai', 'sw-channels'], what: 'How Aleph shows up in Google results, ads and AI answers for its name and category.', finding: 'Nobody defends our brand term{{Paid is 0.38% of keyword traffic (Similarweb).}}. OneStream bids on "aleph fp&a".' },
  { group: 'Product', sub: 'Web', surface: 'Answer pages (/answers)', owner: 'Shared', what: 'SEO pages that each answer one FP&A question.', finding: 'They rank well{{#1 organic result for "ai fp&a software," cited in Google\'s AI Overview.}}, and they read as written for search engines. None carries a point of view a person would repeat.' },
  { group: 'Product', sub: 'Web', surface: 'Integrations directory', owner: 'Aleph', what: 'The /integrations page listing every connector.', finding: 'The count differs across surfaces (150+ vs 200+){{Site: "150+ integrations." Sage Intacct listing: "200+ integrations."}}, and integration pages still link to /demo-old.' },
  { group: 'Product', sub: 'Web', surface: 'Interactive tools (FP&A fitness test, AI spend calculator)', owner: 'Red Antler', photos: ['flow-06'], what: 'The fitness quiz (a Replit app) and the AI spend calculator.', finding: 'The fitness test asks for contact details before its first question, and the calculator speaks to engineers.' },
  { group: 'Product', sub: 'Web', surface: 'Mobile web', owner: 'Shared', what: 'The site on a phone.', finding: 'About 32 seconds to show the main content and 8.6 MB.' },
  { group: 'Product', sub: 'Web', surface: 'Site pop-ups (HubSpot top banner, exit modal)', owner: 'Aleph', assigned: 'Jack (HubSpot)', photos: ['flow-01', 'flow-02'], what: "HubSpot's top banner and the exit-intent modal.", finding: 'The exit modal offers 15 minutes and opens a page asking for 30.' },
]

export function surfaceCounts(rows) {
  const c = { total: rows.length, 'Red Antler': 0, Shared: 0, Aleph: 0 }
  for (const r of rows) c[r.owner]++
  return c
}

// Where Daniel wants to invest over the next 6 months (Sep 17 review + his
// written notes). "urgent" is his fire emoji: invest, and it's burning.
export const PRIORITY = {
  urgent: { label: 'Priority 1', chip: 'amchip warm', note: 'Invest, and burning' },
  invest: { label: 'Priority 2', chip: 'amchip done', note: 'Invest more' },
  discuss: { label: 'Discuss', chip: 'amchip blue', note: 'Worth more discussion' },
  hold: { label: 'Hold', chip: 'amchip', note: "Don't invest more" },
  oob: { label: 'Not brand', chip: 'amchip', note: 'Out of bounds for brand' },
}

export function priorityCounts(rows) {
  const c = { urgent: 0, invest: 0, discuss: 0, hold: 0, oob: 0, none: 0 }
  for (const r of rows) c[r.priority || 'none']++
  return c
}

// Images added by hand, outside the audit export (which owns data.json).
export const PHOTOS = {
  'event-badges': { w: 480, h: 640, alt: 'Name badges on lanyards laid out on the check-in desk', caption: 'Check-in: badges with name, title and company' },
  'event-food': { w: 640, h: 480, alt: 'Breakfast spread of bagels, fruit, bars and cookies', caption: 'Food at Mindspace' },
  'event-room': { w: 480, h: 640, alt: 'Event room set with long tables, fidget cubes and a projector screen', caption: 'The room, before doors' },
  'event-entry': { w: 480, h: 640, alt: 'Aleph pull-up banner beside the Mindspace entrance', caption: 'The banner at the door' },
  'event-banner': { w: 480, h: 640, alt: 'Aleph banner: AI-native FP&A trusted and loved by industry leaders, with customer logos', caption: '"AI-native FP&A trusted and loved by industry leaders"' },
  'event-fidget': { w: 480, h: 640, alt: 'Black fidget cube printed with the Aleph logo and Stress-free FP&A', caption: 'Fidget cube: "Stress-free FP&A"' },
  'event-bottle': { w: 480, h: 640, alt: 'Black water bottle with the Aleph logo etched in', caption: 'Water bottle, etched mark' },
}
for (const [k, v] of Object.entries(PHOTOS)) {
  v.src = `/aleph/audit/img/${k}.webp`
  v.full = `/aleph/audit/img/${k}-lg.webp`
}
